// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiUpin.Infrastructure.Persistence;

namespace SiUpin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SiUpinDBContext))]
    [Migration("20201029083535_SiUpinDB_001")]
    partial class SiUpinDB_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiUpin.Domain.Entities.AsalBantuan", b =>
                {
                    b.Property<string>("AsalBantuanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("AsalBantuanID");

                    b.HasIndex("AsalBantuanID");

                    b.ToTable("AsalBantuans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Berita", b =>
                {
                    b.Property<string>("BeritaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("id_berita")
                        .HasColumnType("text");

                    b.HasKey("BeritaID");

                    b.HasIndex("BeritaID");

                    b.ToTable("Beritas");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.File", b =>
                {
                    b.Property<string>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EntityType")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UphID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UphProdukID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .HasColumnType("varchar(50)");

                    b.HasKey("FileID");

                    b.HasIndex("EntityID");

                    b.HasIndex("FileID");

                    b.HasIndex("UphID");

                    b.HasIndex("UphProdukID");

                    b.HasIndex("UserID");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.JenisKomoditi", b =>
                {
                    b.Property<string>("JenisKomoditiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_komoditi")
                        .HasColumnType("varchar(50)");

                    b.HasKey("JenisKomoditiID");

                    b.HasIndex("JenisKomoditiID");

                    b.ToTable("JenisKomoditis");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.JenisTernak", b =>
                {
                    b.Property<string>("JenisTernakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_ternak")
                        .HasColumnType("varchar(50)");

                    b.HasKey("JenisTernakID");

                    b.HasIndex("JenisTernakID");

                    b.ToTable("JenisTernaks");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kecamatan", b =>
                {
                    b.Property<string>("KecamatanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KotaID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_kecamatan")
                        .HasColumnType("varchar(50)");

                    b.HasKey("KecamatanID");

                    b.HasIndex("KecamatanID");

                    b.HasIndex("KotaID");

                    b.ToTable("Kecamatans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kelurahan", b =>
                {
                    b.Property<string>("KelurahanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KecamatanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_kelurahan")
                        .HasColumnType("varchar(50)");

                    b.HasKey("KelurahanID");

                    b.HasIndex("KecamatanID");

                    b.HasIndex("KelurahanID");

                    b.ToTable("Kelurahans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kota", b =>
                {
                    b.Property<string>("KotaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProvinsiID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_kota")
                        .HasColumnType("varchar(50)");

                    b.HasKey("KotaID");

                    b.HasIndex("KotaID");

                    b.HasIndex("ProvinsiID");

                    b.ToTable("Kotas");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterAspek", b =>
                {
                    b.Property<string>("ParameterAspekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_aspek")
                        .HasColumnType("text");

                    b.HasKey("ParameterAspekID");

                    b.HasIndex("ParameterAspekID");

                    b.ToTable("ParameterAspeks");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterIndikator", b =>
                {
                    b.Property<string>("ParameterIndikatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParameterKriteriaID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_indikator")
                        .HasColumnType("text");

                    b.HasKey("ParameterIndikatorID");

                    b.HasIndex("ParameterIndikatorID");

                    b.HasIndex("ParameterKriteriaID");

                    b.ToTable("ParameterIndikators");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterJawaban", b =>
                {
                    b.Property<string>("ParameterJawabanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParameterIndikatorID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Skor")
                        .HasColumnType("char(5)");

                    b.HasKey("ParameterJawabanID");

                    b.HasIndex("ParameterIndikatorID");

                    b.HasIndex("ParameterJawabanID");

                    b.ToTable("ParameterJawabans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterKriteria", b =>
                {
                    b.Property<string>("ParameterKriteriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParameterAspekID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_kriteria")
                        .HasColumnType("text");

                    b.HasKey("ParameterKriteriaID");

                    b.HasIndex("ParameterAspekID");

                    b.HasIndex("ParameterKriteriaID");

                    b.ToTable("ParameterKriterias");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Pesan", b =>
                {
                    b.Property<string>("PesanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PesanID");

                    b.HasIndex("PesanID");

                    b.ToTable("Pesans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ProdukOlahan", b =>
                {
                    b.Property<string>("ProdukOlahanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("JenisKomoditiID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("id_olahan")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProdukOlahanID");

                    b.HasIndex("JenisKomoditiID");

                    b.HasIndex("ProdukOlahanID");

                    b.ToTable("ProdukOlahans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Provinsi", b =>
                {
                    b.Property<string>("ProvinsiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id_provinsi")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProvinsiID");

                    b.HasIndex("ProvinsiID");

                    b.ToTable("Provinsis");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Satuan", b =>
                {
                    b.Property<string>("SatuanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("SatuanID");

                    b.HasIndex("SatuanID");

                    b.ToTable("Satuans");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Uph", b =>
                {
                    b.Property<string>("UphID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Alamat")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Handphone")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KecamatanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KelurahanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ketua")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KotaID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProvinsiID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TahunBerdiri")
                        .HasColumnType("char(5)");

                    b.Property<string>("id_uph")
                        .HasColumnType("text");

                    b.HasKey("UphID");

                    b.HasIndex("KecamatanID");

                    b.HasIndex("KelurahanID");

                    b.HasIndex("KotaID");

                    b.HasIndex("ProvinsiID");

                    b.HasIndex("UphID");

                    b.ToTable("Uphs");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.UphParameter", b =>
                {
                    b.Property<string>("UphID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParameterJawabanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("UphID", "ParameterJawabanID");

                    b.HasIndex("ParameterJawabanID");

                    b.HasIndex("UphID");

                    b.ToTable("UphParameters");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.UphProduk", b =>
                {
                    b.Property<string>("UphProdukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Berat")
                        .HasColumnType("int(5)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Harga")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("JenisTernakID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProdukOlahanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SatuanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UphID")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UphProdukID");

                    b.HasIndex("JenisTernakID");

                    b.HasIndex("ProdukOlahanID");

                    b.HasIndex("SatuanID");

                    b.HasIndex("UphID");

                    b.HasIndex("UphProdukID");

                    b.ToTable("UphProduks");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Alamat")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fullname")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Instansi")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Jabatan")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KecamatanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KelurahanID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KotaID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("NIP")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PictureURL")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ProvinsiID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telepon")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("KecamatanID");

                    b.HasIndex("KelurahanID");

                    b.HasIndex("KotaID");

                    b.HasIndex("ProvinsiID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.File", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Uph", null)
                        .WithMany("Files")
                        .HasForeignKey("UphID");

                    b.HasOne("SiUpin.Domain.Entities.UphProduk", null)
                        .WithMany("Files")
                        .HasForeignKey("UphProdukID");

                    b.HasOne("SiUpin.Domain.Entities.User", null)
                        .WithMany("Files")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kecamatan", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Kota", "Kota")
                        .WithMany("Kecamatans")
                        .HasForeignKey("KotaID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kelurahan", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Kecamatan", "Kecamatan")
                        .WithMany("Kelurahans")
                        .HasForeignKey("KecamatanID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Kota", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Provinsi", "Provinsi")
                        .WithMany("Kotas")
                        .HasForeignKey("ProvinsiID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterIndikator", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.ParameterKriteria", "ParameterKriteria")
                        .WithMany("ParameterIndikators")
                        .HasForeignKey("ParameterKriteriaID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterJawaban", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.ParameterIndikator", "ParameterIndikator")
                        .WithMany("ParameterJawabans")
                        .HasForeignKey("ParameterIndikatorID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ParameterKriteria", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.ParameterAspek", "ParameterAspek")
                        .WithMany("ParameterKriterias")
                        .HasForeignKey("ParameterAspekID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.ProdukOlahan", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.JenisKomoditi", "JenisKomoditi")
                        .WithMany("ProdukOlahans")
                        .HasForeignKey("JenisKomoditiID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.Uph", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Kecamatan", "Kecamatan")
                        .WithMany("Uphs")
                        .HasForeignKey("KecamatanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Kelurahan", "Kelurahan")
                        .WithMany("Uphs")
                        .HasForeignKey("KelurahanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Kota", "Kota")
                        .WithMany("Uphs")
                        .HasForeignKey("KotaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Provinsi", "Provinsi")
                        .WithMany("Uphs")
                        .HasForeignKey("ProvinsiID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.UphParameter", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.ParameterJawaban", "ParameterJawaban")
                        .WithMany("UphParameters")
                        .HasForeignKey("ParameterJawabanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiUpin.Domain.Entities.Uph", "Uph")
                        .WithMany("UphParameters")
                        .HasForeignKey("UphID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.UphProduk", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.JenisTernak", "JenisTernak")
                        .WithMany("UphProduks")
                        .HasForeignKey("JenisTernakID");

                    b.HasOne("SiUpin.Domain.Entities.ProdukOlahan", "ProdukOlahan")
                        .WithMany("UphProduks")
                        .HasForeignKey("ProdukOlahanID");

                    b.HasOne("SiUpin.Domain.Entities.Satuan", "Satuan")
                        .WithMany("UphProduks")
                        .HasForeignKey("SatuanID");

                    b.HasOne("SiUpin.Domain.Entities.Uph", "Uph")
                        .WithMany("UphProduks")
                        .HasForeignKey("UphID");
                });

            modelBuilder.Entity("SiUpin.Domain.Entities.User", b =>
                {
                    b.HasOne("SiUpin.Domain.Entities.Kecamatan", "Kecamatan")
                        .WithMany("Users")
                        .HasForeignKey("KecamatanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Kelurahan", "Kelurahan")
                        .WithMany("Users")
                        .HasForeignKey("KelurahanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Kota", "Kota")
                        .WithMany("Users")
                        .HasForeignKey("KotaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Provinsi", "Provinsi")
                        .WithMany("Users")
                        .HasForeignKey("ProvinsiID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiUpin.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
